### ISSUE TITLE
pic

### ISSUE THREAD

**Issue by kanade9** [kzmaro/GyudonPurchase#1]
<img width="1024" alt="menu" src="https://user-images.githubusercontent.com/47267817/57543853-85df4e80-7390-11e9-991b-9cfb82fe54d7.png">

**Comment by kanade9** [comment]
<img width="1024" alt="careful" src="https://user-images.githubusercontent.com/47267817/57543869-92fc3d80-7390-11e9-99c5-9f4129e6ce63.png">

**Comment by kanade9** [comment]
<img width="512" alt="menu" src="https://user-images.githubusercontent.com/47267817/57544086-46fdc880-7391-11e9-8d48-6c37b2c13a65.png">

**Comment by kanade9** [comment]
<img width="510" alt="スクリーンショット 2019-05-11 2 16 54" src="https://user-images.githubusercontent.com/47267817/57544642-e079aa00-7392-11e9-92bf-c350aecf1d45.png">

**Comment by kanade9** [comment]
<img width="510" alt="スクリーンショット 2019-05-11 2 18 52" src="https://user-images.githubusercontent.com/47267817/57544704-25054580-7393-11e9-969a-83c5120b537e.png">

**Comment by kzmaro** [comment]
<img width="125" alt="menu" src="https://user-images.githubusercontent.com/47267817/57548187-4ec26a80-739b-11e9-85ff-ce6afa7f66d0.png">

**Comment by kzmaro** [comment]
<img width="125" alt="スクリーンショット 2019-05-11 2 18 52" src="https://user-images.githubusercontent.com/47267817/57548208-54b84b80-739b-11e9-87e1-2274777efe09.png">

**Comment by kanade9** [comment]
<img width="512" alt="careful" src="https://user-images.githubusercontent.com/47267817/57548398-c8f2ef00-739b-11e9-84a3-c0bba93b7ef6.png">

**Comment by kanade9** [comment]
<img width="510" alt="スクリーンショット 2019-05-11 3 30 12" src="https://user-images.githubusercontent.com/47267817/57548936-2f2c4180-739d-11e9-8f4d-ce1363c707a6.png">

**Comment by kanade9** [comment]
![Uploading スクリーンショット 2019-05-11 2.16.54.png…]()

**Comment by kanade9** [comment]
<img width="512" alt="スクリーンショット 2019-05-11 3 33 39" src="https://user-images.githubusercontent.com/47267817/57549129-b083d400-739d-11e9-9f7c-1f9f7016ba43.png">
